name: Test
on: push

jobs:
    #   test_3.8:
    #     name: Build wheels on ${{ matrix.os }}
    #     runs-on: ${{ matrix.os }}
    #     strategy:
    #       fail-fast: false
    #       matrix:
    #         os: [ubuntu-latest, windows-latest]

    #     steps:
    #       - uses: actions/checkout@v4
    #         with:
    #           submodules: recursive

    #       - name: Set up Python
    #         uses: actions/setup-python@v5
    #         if: matrix.os == 'ubuntu-latest'
    #         with:
    #           python-version: '3.8'

    #       - name: Install
    #         run: pip install .[tests]

    #       - name: Run tests
    #         run: pytest -vs ./tests/EndianedBinaryIO

    test_313:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install
              run: pip install .[tests]

            - name: Run tests
              run: pytest -vs
              working-directory: ./tests
